services:
  treafik-reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--providers.docker"
      - "--api=true"
      # - "--certificatesresolvers.default-resolver.acme.httpchallenge=true"
      # - "--certificatesresolvers.default-resolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.default-resolver.acme.email=20523134@students.uii.ac.id"
      # - "--certificatesresolvers.default-resolver.acme.storage=/letsencrypt/acme.json"

      - "--entrypoints.web.address=:8000"
      - "--entrypoints.websecure.address=:4430"
      - "--entrypoints.web-decoy.address=:8080"
      - "--entrypoints.websecure-decoy.address=:4433"

      - "--log.level=DEBUG" # Set log level to DEBUG for detailed logs
      - "--log.filePath=/logs/traefik.log" # Set log file path for Traefik logs
    networks:
      - cf-network
      - nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - "./logs:/logs"
      - "./configs:/configs"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`tf-dashboard.ninomae.my.id`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=yume:$$apr1$$R2KU7RNj$$x3Tpu8Y3z/y8LceGbYDzt/"

      - "traefik.providers.http.routers.router-http.entrypoints=web,websecure" # HTTP router entry point
      - "traefik.providers.http.routers.router-http.rule=Host(`api.ninomae.my.id`)" # Rule for HTTP router
      - "traefik.providers.http.routers.router-http.service=c2-http-service" # Service for HTTP router
      - "traefik.http.services.c2-http-service.loadbalancer.server.url=http://host.docker.internal:80" # URL for HTTP service
      - "traefik.http.services.c2-http-service.loadbalancer.passHostHeader=true" # Pass the host header to the Nginx service


      # - "traefik.providers.http.routers.router-https.entrypoints=websecure" # HTTPS router entry point
      # - "traefik.providers.http.routers.router-https.rule=Host(`api.ninomae.my.id`)" # Rule for HTTPS router
      # - "traefik.providers.http.routers.router-https.service=c2-https-service" # Service for HTTPS router
      # - "traefik.http.services.c2-https-service.loadbalancer.server.url=http://host.docker.internal:443" # URL for HTTPS service
      # - "traefik.http.services.c2-https-service.loadbalancer.passHostHeader=true" # Pass the host header to the Nginx service


      - "traefik.http.routers.nginx.rule=Host(`ninomae.my.id`) || Host(`www.ninomae.my.id`)" # Rule for Nginx decoy website
      - "traefik.http.routers.nginx.entrypoints=web-decoy,websecure-decoy" # Entry points for Nginx decoy website
      - "traefik.http.routers.nginx.service=nginx-service" # Service for Nginx decoy website
      - "traefik.http.services.nginx-service.loadbalancer.server.url=http://nginx:80" # URL for Nginx service
      - "traefik.http.services.nginx-service.loadbalancer.passHostHeader=true" # Pass the host header to the Nginx service

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    networks:
      - nginx
    volumes:
      - "./nginx/var/www/html:/usr/share/nginx/html" # Mount the decoy website files to the Nginx container
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    labels:
      - "traefik.enable=true" # Enable Traefik for this service

  # Cloudflare Tunnel Service
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest # Pull the latest version of the Cloudflare Tunnel image
    container_name: cloudflare-tunnel # Name of the Cloudflare Tunnel container
    hostname: cloudflare-tunnel # Hostname for the Cloudflare Tunnel container
    restart: unless-stopped # Restart the container unless manually stopped

    # Network mode configuration
    networks:
      - cf-network

    # Command to run Cloudflare Tunnel
    command: tunnel run # Command to start the Cloudflare tunnel

    # Volume configuration for time synchronization and hosts file persistence
    volumes:
      - /etc/localtime:/etc/localtime:ro # Synchronize time with the host

    # Environment variables for Cloudflare Tunnel
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}" # Pass the Cloudflare Tunnel token from environment variable

    labels:
      - "traefik.enable=false" # Disable Traefik for this service

networks:
  cf-network:
  nginx:
