################################################################
#
# Configuration sample for Traefik v2.
#
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################

# EntryPoints definition
#
# Optional
#
entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  web-decoy:
    address: :8080

  websecure-decoy:
    address: :4433

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
#
# Optional
#
api:
  # Enable the API in insecure mode
  #
  # Optional
  # Default: false
  #
 insecure: false

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
 dashboard: true

################################################################
# Docker configuration backend
################################################################

providers:
  # Enable Docker configuration backend
 docker:
    # Docker server endpoint. Can be a tcp or a unix socket endpoint.
    #
    # Required
    # Default: "unix:///var/run/docker.sock"
    #
#    endpoint: tcp://10.10.10.10:2375

    # Default host rule.
    #
    # Optional
    # Default: "Host(`{{ normalize .Name }}`)"
    #
#    defaultRule: Host(`{{ normalize .Name }}.docker.localhost`)

    # Expose containers by default in traefik
    #
    # Optional
    # Default: true
    #
#    exposedByDefault: false
  file:
    filename: "./configs/file.provider.yaml"
    watch: true

  http:
    filename: "./configs/http.provider.yaml"
    watch: true

# Dynamic Configuration
http:
  routers:
    dashboard:
      rule: Host(`tf-dashboard.ninomae.my.id`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "yume:read-the-docs-pls"

certificatesResolvers:
  default-resolver:
    acme:
      email: 20523134@students.uiia.c.id
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
